apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    run: test-app  
spec:
  containers:
  - image: registry.gitlab.com/prohoho/app-test/sample:v1
    name: test-app
  restartPolicy: Always
  imagePullSecrets:
    - name: test-secret