apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-svc
  name: test-svc
spec:
  ports:
  - name: test-svc
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: test-app
  type: NodePort
status:
  loadBalancer: {}
